# Generated by Django 4.2.24 on 2025-09-15 20:51

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена')),
                ('image', models.ImageField(blank=True, help_text='Формат: JPG, PNG. Максимальный размер: 2MB', upload_to='products/', verbose_name='Изображение')),
                ('category', models.CharField(choices=[('BOUQUET', 'Букеты'), ('POT', 'Комнактные расстения'), ('DRIED', 'Сухоцветы'), ('ACCESSORY', 'Аксессуары')], default='BOUQUET', max_length=20, verbose_name='Категория')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
    ]
