# Generated by Django 4.2.24 on 2025-09-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, help_text='Полный адрес с индексом', verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True, help_text='Пожелания по доставке или особые указания', verbose_name='Комментарии к заказу'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон для связи'),
        ),
    ]
